version: '3.2'


networks:
  php-nginx-mysql8:


services:

  #nginx
  nginx-service:
    image: nginx:stable
    container_name: nginx-container
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      # Change link below depending on project root
      - ../../Projects/LinkTracker:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - mysql8-service
    networks:
      - php-nginx-mysql8


  #php
  php82-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - ../../Projects/LinkTracker:/var/www/project
    networks:
      - php-nginx-mysql8
      

  #mysql
  mysql8-service:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment: # defines user with password from .env file, also defines root user with same password as user
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - php-nginx-mysql8



  #phpmydamin service
  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql8-service
      - PMA_PORT=3306
    networks:
      - php-nginx-mysql8